USE TestDB
GO

CREATE TABLE test.Products(
    Id INT IDENTITY(1, 1) NOT NULL,
    Name NVARCHAR(16) NOT NULL,
    Colour NVARCHAR(16),

    CONSTRAINT PK_Product_Id PRIMARY KEY CLUSTERED(Id),
)
GO

CREATE TABLE test.Stock(
    ProductId INT NOT NULL,
    Count INT NOT NULL CONSTRAINT DF_Stock_Count DEFAULT 0,

    CONSTRAINT FK_Stock_ProductId FOREIGN KEY (ProductId) REFERENCES test.Products(Id) ON DELETE CASCADE
)
GO
