USE master

ALTER LOGIN SA WITH PASSWORD='Password1!'
GO

USE TestDB
GO

CREATE SCHEMA test
GO

CREATE LOGIN ServiceUser WITH PASSWORD='Password2!', DEFAULT_DATABASE=TestDb
CREATE USER ServiceUser WITH DEFAULT_SCHEMA=test
GRANT SELECT ON SCHEMA::test TO ServiceUser
GRANT INSERT ON SCHEMA::test TO ServiceUser
GRANT UPDATE ON SCHEMA::test TO ServiceUser
GRANT DELETE ON SCHEMA::test TO ServiceUser
GRANT EXECUTE ON SCHEMA::test TO ServiceUser
GO

CREATE LOGIN UpdateUser WITH PASSWORD='Password3!', DEFAULT_DATABASE = TestDb
CREATE USER UpdateUser
ALTER ROLE db_ddladmin ADD MEMBER UpdateUser
GO
